apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/assetdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SERVER_PORT: "8085"